
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-6pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-6pm-3
pull_requests: [{"author":{"id":"U_kgDOB3CMjQ","is_bot":false,"login":"jenniferlopez17","name":""},"headRefName":"Jennifer-RecommendationRequest-index","number":103,"title":"JL - Index Page for RecommendationRequest plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-3/pull/103"}]
