
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-6pm-3
owner: ucsb-cs156-w24
repo_name: team03-w24-6pm-3
pull_requests: [{"author":{"id":"U_kgDOB3CMjQ","is_bot":false,"login":"jenniferlopez17","name":""},"headRefName":"Jennifer-README","number":113,"title":"JL - Updated README","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-3/pull/113"},{"author":{"id":"U_kgDOB3CMjQ","is_bot":false,"login":"jenniferlopez17","name":""},"headRefName":"Jennifer-Navbar","number":112,"title":"JL - Removed extra Placeholder tab in NavBar","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-3/pull/112"},{"author":{"id":"U_kgDOBX3m_g","is_bot":false,"login":"welaalice","name":"Towela Phiri"},"headRefName":"TP-UCSBOrganizations-App","number":111,"title":"TP - Fixing App.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-3/pull/111"},{"author":{"id":"U_kgDOBh72PQ","is_bot":false,"login":"andyjin1","name":"Andy Jin"},"headRefName":"AJ-Debug2","number":109,"title":"AJ - Fixed UCSB orgnization","url":"https://github.com/ucsb-cs156-w24/team03-w24-6pm-3/pull/109"}]
